name: Deploy Storybook

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: storybook
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Build Storybook
        run: |
          npm install
          npm run build-storybook
      - name: Commit & Push
        working-directory: storybook
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          NAME: "Github Actions"
          EMAIL: "madamebiz@monsieurbiz.com"
        run: |
          git config user.email "${EMAIL}"
          git config user.name "${NAME}"
          git add -A
          git commit -sm "${{ github.event.head_commit.message }}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push
